### ISSUE TITLE
[Front] Duplikowanie formularza 

### ISSUE THREAD

**Issue by aldor007** [Teleinformatyka/RedSparrowFront#14]
http://i.imgur.com/qeCIAYg.png Drugie logo i miejsce na formularz nie powinny się pojawiać. Ten bład powinie być raczej pod logiem

**Comment by iryont** [comment]
Błąd będzie nad formularzem, ale logo można usunąć. To już raczej Tomek zrobi (usunięcia loga).

I jakie miejsce na formularz? Formularz pojawia się, aby poprawić dane, po co się wycofywać do formularza?

**Comment by Aldor007** [comment]
Mnie by się tak podobało http://i.imgur.com/VBNBCh9.png

**Comment by iryont** [comment]
Mi w sumie już też :)

Dobra, to zrobimy tak. Chyba, że masz już kod - to wrzucaj.

**Comment by Aldor007** [comment]
Kod jeszcze nie mam, w sobotę podeślę ;)

**Comment by profhouse** [comment]
Zrobione.
